#!/Users/sumitkumar/Desktop/sumit_exercise/Data_Science/python-exercise/venv/bin/python3.8
import sys
from lib2to3.main import main

sys.exit(main("lib2to3.fixes"))
